"""Compile NeonInk's opaque sRGB/OKLCH tokens. Python 3.11+, standard library only."""
from __future__ import annotations

import argparse
import json
import math
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def linear(v):
    return v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4


def rgb(hex_value):
    return [int(hex_value[i:i + 2], 16) / 255 for i in (1, 3, 5)]


def oklch(hex_value):
    r, g, b = map(linear, rgb(hex_value))
    l = (0.4122214708*r + 0.5363325363*g + 0.0514459929*b) ** (1/3)
    m = (0.2119034982*r + 0.6806995451*g + 0.1073969566*b) ** (1/3)
    s = (0.0883024619*r + 0.2817188376*g + 0.6299787005*b) ** (1/3)
    L = 0.2104542553*l + 0.793617785*m - 0.0040720468*s
    a = 1.9779984951*l - 2.428592205*m + 0.4505937099*s
    b = 0.0259040371*l + 0.7827717662*m - 0.808675766*s
    C = math.hypot(a, b)
    return [L, C, math.degrees(math.atan2(b, a)) % 360 if C > 1e-7 else 0]


def to_linear_srgb(values):
    L, C, H = values
    a, b = C*math.cos(math.radians(H)), C*math.sin(math.radians(H))
    l = (L + 0.3963377774*a + 0.2158037573*b) ** 3
    m = (L - 0.1055613458*a - 0.0638541728*b) ** 3
    s = (L - 0.0894841775*a - 1.291485548*b) ** 3
    return [4.0767416621*l - 3.3077115913*m + 0.2309699292*s,
            -1.2684380046*l + 2.6097574011*m - 0.3413193965*s,
            -0.0041960863*l - 0.7034186147*m + 1.707614701*s]


def contrast(a, b):
    def lum(h):
        return sum(x*y for x, y in zip(map(linear, rgb(h)), (0.2126, 0.7152, 0.0722)))
    low, high = sorted((lum(a), lum(b)))
    return (high + 0.05) / (low + 0.05)


def css_color(values):
    return 'oklch(' + ' '.join(f'{v:.6f}'.rstrip('0').rstrip('.') or '0' for v in values) + ')'


def compile_source(source):
    data = tomllib.loads(source.read_text(encoding='utf-8'))
    if data['meta']['schema'] != 'aptlantis.neonink.tokens/1' or data['meta']['mode'] != 'dark':
        raise ValueError('unsupported schema or mode')
    palette, aliases = data['palette'], data['semantic']
    for name, color in palette.items():
        if not re.fullmatch(r'[a-z][a-z0-9-]*', name):
            raise ValueError(f'invalid palette key: {name}')
        if not re.fullmatch(r'#[0-9A-F]{6}', color['hex']) or not color['role'].strip():
            raise ValueError(f'invalid color/role: {name}')
        values = color['oklch']
        if len(values) != 3 or any(type(v) not in (int, float) or not math.isfinite(v) for v in values):
            raise ValueError(f'invalid OKLCH: {name}')
        if not (0 <= values[0] <= 1 and 0 <= values[1] <= 0.5 and 0 <= values[2] < 360):
            raise ValueError(f'OKLCH range: {name}')
        expected = oklch(color['hex'])
        if any(abs(a-b) > 0.000002 for a,b in zip(values, expected)):
            raise ValueError(f'hex/OKLCH mismatch: {name}')
        if any(v < -0.00001 or v > 1.00001 for v in to_linear_srgb(values)):
            raise ValueError(f'outside sRGB: {name}')
    for name, ref in aliases.items():
        if not re.fullmatch(r'[a-z][a-z0-9-]*', name) or ref not in palette:
            raise ValueError(f'invalid semantic reference: {name} -> {ref}')
    for name, refs in data['scales'].items():
        if len(refs) < 3 or any(ref not in palette for ref in refs):
            raise ValueError(f'invalid scale: {name}')
        levels = [palette[r]['oklch'][0] for r in refs]
        if name.startswith('sequential') and any(a >= b for a,b in zip(levels, levels[1:])):
            raise ValueError(f'non-monotonic sequential lightness: {name}')
    checks = []
    for pair in data['contrast']['pairs']:
        fg, bg, minimum = pair.split('|')
        minimum = float(minimum)
        if minimum not in (3.0, 4.5, 7.0):
            raise ValueError('unsupported contrast threshold')
        ratio = contrast(palette[aliases[fg]]['hex'], palette[aliases[bg]]['hex'])
        checks.append({'foreground': fg, 'background': bg, 'ratio': round(ratio, 4), 'minimum': minimum})
        if ratio < minimum:
            raise ValueError(f'contrast failure: {fg}/{bg} {ratio:.3f} < {minimum}')
    lines = ['/* Generated by tools/compile_neonink.py; edit TOML. */', ':root, .neonink {']
    for name, color in palette.items():
        lines.append(f'  --ni-palette-{name}: {color["hex"]};')
    for name, ref in aliases.items():
        lines.append(f'  --ni-{name}: var(--ni-palette-{ref});')
    lines += ['}', '@supports (color: oklch(0 0 0)) {', '  :root, .neonink {']
    lines += [f'    --ni-palette-{n}: {css_color(c["oklch"])};' for n,c in palette.items()]
    lines += ['  }', '}']
    report = {'version': data['meta']['version'], 'palette_count': len(palette), 'checks': checks,
              'limits': 'Opaque declared pairs only; not a rendered WCAG conformance claim.'}
    table = ['# NeonInk color representations', '', 'Exact legacy colors are preserved. New scale stops are labeled in the source.', '', '| Token | Before / sRGB fallback | After / OKLCH representation |', '| --- | --- | --- |']
    table += [f'| {n} | `{c["hex"]}` | `{css_color(c["oklch"])}` |' for n,c in palette.items()]
    return {'NeonInk.Tokens.css': '\n'.join(lines)+'\n',
            'NeonInk.Tokens.json': json.dumps(data, indent=2)+'\n',
            'contrast-report.json': json.dumps(report, indent=2)+'\n',
            'Color-Representations.md': '\n'.join(table)+'\n'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT/'spec/tokens/NeonInk.Tokens.toml')
    parser.add_argument('--output', type=Path, default=ROOT/'generated')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        outputs = compile_source(args.source)
        stale = []
        for name, text in outputs.items():
            path = args.output/name
            payload = text.encode('utf-8')
            if args.check:
                if not path.exists() or path.read_bytes() != payload:
                    stale.append(name)
            else:
                args.output.mkdir(parents=True, exist_ok=True)
                path.write_bytes(payload)
        if stale:
            raise ValueError('missing/stale: ' + ', '.join(stale))
        print(f'PASS: {len(outputs)} outputs ' + ('verified without writes' if args.check else 'generated'))
        return 0
    except (ValueError, KeyError, TypeError, OSError) as exc:
        print(f'FAIL: {exc}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
